apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: order-service
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP