apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: velero
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=YOUR_ACCESS_KEY
    aws_secret_access_key=YOUR_SECRET_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
  labels:
    app: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero
  template:
    metadata:
      labels:
        app: velero
    spec:
      serviceAccountName: velero
      containers:
      - name: velero
        image: velero/velero:v1.12.0
        command:
        - /velero
        args:
        - server
        - --provider=aws
        - --bucket=YOUR_S3_BUCKET
        - --backup-location-config=region=us-west-2
        - --snapshot-location-config=region=us-west-2
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        volumeMounts:
        - name: cloud-credentials
          mountPath: /credentials
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: cloud-credentials
        secret:
          secretName: cloud-credentials